name: Build and Run

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  
          
      - name: Debug Secrets
        run: |
          echo "Checking if secrets are available..."
          echo "SONAR_HOST_URL: $SONAR_HOST_URL"
          [[ -z "$SONAR_TOKEN" ]] && echo "SONAR_TOKEN is missing!" || echo "SONAR_TOKEN is set!"
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: SonarQube Analysis
        uses: SonarSource/sonarqube-scan-action@v5.0.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

  run-python:
    name: Run Python Script
    runs-on: ubuntu-latest
    needs: build  # Ensures this runs only after 'build' is successful

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Run Python script
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
        run: python gsoc2025/GSOC.py
